name: Test
on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Cache for pip
      uses: actions/cache@v1
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ matrix.os }}-cache-pip

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies & Test
      run: |
        pip install --upgrade -r requirements.txt
        python setup.py install
        python test.py
